package ru.laushkina.rates.ui

import android.util.Log
import android.util.Pair
import ru.laushkina.rates.R
import ru.laushkina.rates.model.RateShortName

class RateFullName {
    companion object {
        private const val TAG = "[RateFullName]"

        fun getFullName(shortName: RateShortName): Pair<Int, Int> {
            return when (shortName) {
                RateShortName.AED -> Pair(R.string.rates_aud, R.drawable.ic_rate_unknown_image)
                RateShortName.AFN -> Pair(R.string.rates_afn, R.drawable.ic_rate_unknown_image)
                RateShortName.ALL -> Pair(R.string.rates_all, R.drawable.ic_rate_unknown_image)
                RateShortName.AMD -> Pair(R.string.rates_amd, R.drawable.ic_rate_unknown_image)
                RateShortName.ANG -> Pair(R.string.rates_ang, R.drawable.ic_rate_unknown_image)
                RateShortName.AOA -> Pair(R.string.rates_aoa, R.drawable.ic_rate_unknown_image)
                RateShortName.ARS -> Pair(R.string.rates_ars, R.drawable.ic_rate_unknown_image)
                RateShortName.AUD -> Pair(R.string.rates_aud, R.drawable.ic_rate_aud_image)
                RateShortName.AWG -> Pair(R.string.rates_awg, R.drawable.ic_rate_unknown_image)
                RateShortName.AZN -> Pair(R.string.rates_azn, R.drawable.ic_rate_unknown_image)
                RateShortName.BAM -> Pair(R.string.rates_bam, R.drawable.ic_rate_unknown_image)
                RateShortName.BBD -> Pair(R.string.rates_bbd, R.drawable.ic_rate_unknown_image)
                RateShortName.BDT -> Pair(R.string.rates_bdt, R.drawable.ic_rate_unknown_image)
                RateShortName.BGN -> Pair(R.string.rates_bgn, R.drawable.ic_rate_bgn_image)
                RateShortName.BHD -> Pair(R.string.rates_bhd, R.drawable.ic_rate_unknown_image)
                RateShortName.BIF -> Pair(R.string.rates_bif, R.drawable.ic_rate_unknown_image)
                RateShortName.BMD -> Pair(R.string.rates_bmd, R.drawable.ic_rate_unknown_image)
                RateShortName.BND -> Pair(R.string.rates_bnd, R.drawable.ic_rate_unknown_image)
                RateShortName.BOB -> Pair(R.string.rates_bob, R.drawable.ic_rate_unknown_image)
                RateShortName.BRL -> Pair(R.string.rates_brl, R.drawable.ic_rate_brl_image)
                RateShortName.BSD -> Pair(R.string.rates_bsd, R.drawable.ic_rate_unknown_image)
                RateShortName.BTC -> Pair(R.string.rates_btc, R.drawable.ic_rate_unknown_image)
                RateShortName.BTN -> Pair(R.string.rates_btn, R.drawable.ic_rate_unknown_image)
                RateShortName.BWP -> Pair(R.string.rates_bwp, R.drawable.ic_rate_unknown_image)
                RateShortName.BYN -> Pair(R.string.rates_byn, R.drawable.ic_rate_unknown_image)
                RateShortName.BYR -> Pair(R.string.rates_byr, R.drawable.ic_rate_unknown_image)
                RateShortName.BZD -> Pair(R.string.rates_bzd, R.drawable.ic_rate_unknown_image)
                RateShortName.CAD -> Pair(R.string.rates_cad, R.drawable.ic_rate_cad_image)
                RateShortName.CDF -> Pair(R.string.rates_cdf, R.drawable.ic_rate_unknown_image)
                RateShortName.CHF -> Pair(R.string.rates_chf, R.drawable.ic_rate_unknown_image)
                RateShortName.CLP -> Pair(R.string.rates_clp, R.drawable.ic_rate_unknown_image)
                RateShortName.CLF -> Pair(R.string.rates_clf, R.drawable.ic_rate_chf_image)
                RateShortName.CNY -> Pair(R.string.rates_cny, R.drawable.ic_rate_chy_image)
                RateShortName.COP -> Pair(R.string.rates_cop, R.drawable.ic_rate_unknown_image)
                RateShortName.CRC -> Pair(R.string.rates_crc, R.drawable.ic_rate_unknown_image)
                RateShortName.CUC -> Pair(R.string.rates_cuc, R.drawable.ic_rate_unknown_image)
                RateShortName.CUP -> Pair(R.string.rates_cup, R.drawable.ic_rate_unknown_image)
                RateShortName.CVE -> Pair(R.string.rates_cve, R.drawable.ic_rate_unknown_image)
                RateShortName.CZK -> Pair(R.string.rates_czk, R.drawable.ic_rate_czk_image)
                RateShortName.DJF -> Pair(R.string.rates_czk, R.drawable.ic_rate_unknown_image)
                RateShortName.EUR -> Pair(R.string.rates_eur, R.drawable.ic_rate_eur_image)
                RateShortName.DKK -> Pair(R.string.rates_dkk, R.drawable.ic_rate_dkk_image)
                RateShortName.DOP -> Pair(R.string.rates_dop, R.drawable.ic_rate_unknown_image)
                RateShortName.DZD -> Pair(R.string.rates_dzd, R.drawable.ic_rate_unknown_image)
                RateShortName.EGP -> Pair(R.string.rates_egp, R.drawable.ic_rate_unknown_image)
                RateShortName.ERN -> Pair(R.string.rates_ern, R.drawable.ic_rate_unknown_image)
                RateShortName.ETB -> Pair(R.string.rates_etb, R.drawable.ic_rate_unknown_image)
                RateShortName.FJD -> Pair(R.string.rates_fjd, R.drawable.ic_rate_unknown_image)
                RateShortName.FKP -> Pair(R.string.rates_fkp, R.drawable.ic_rate_unknown_image)
                RateShortName.GBP -> Pair(R.string.rates_gbp, R.drawable.ic_rate_gbp_image)
                RateShortName.GEL -> Pair(R.string.rates_gel, R.drawable.ic_rate_unknown_image)
                RateShortName.GGP -> Pair(R.string.rates_ggp, R.drawable.ic_rate_unknown_image)
                RateShortName.GIP -> Pair(R.string.rates_gip, R.drawable.ic_rate_unknown_image)
                RateShortName.GMD -> Pair(R.string.rates_gmd, R.drawable.ic_rate_unknown_image)
                RateShortName.GNF -> Pair(R.string.rates_gnf, R.drawable.ic_rate_unknown_image)
                RateShortName.GTQ -> Pair(R.string.rates_gtq, R.drawable.ic_rate_unknown_image)
                RateShortName.GYD -> Pair(R.string.rates_gyd, R.drawable.ic_rate_unknown_image)
                RateShortName.GHS -> Pair(R.string.rates_ghs, R.drawable.ic_rate_unknown_image)
                RateShortName.HKD -> Pair(R.string.rates_hkd, R.drawable.ic_rate_hkd_image)
                RateShortName.HRK -> Pair(R.string.rates_hrk, R.drawable.ic_rate_hrk_image)
                RateShortName.HUF -> Pair(R.string.rates_huf, R.drawable.ic_rate_huf_image)
                RateShortName.IDR -> Pair(R.string.rates_idr, R.drawable.ic_rate_idr_image)
                RateShortName.ILS -> Pair(R.string.rates_ils, R.drawable.ic_rate_ils_image)
                RateShortName.HNL -> Pair(R.string.rates_hnl, R.drawable.ic_rate_unknown_image)
                RateShortName.HTG -> Pair(R.string.rates_htg, R.drawable.ic_rate_unknown_image)
                RateShortName.IMP -> Pair(R.string.rates_imp, R.drawable.ic_rate_unknown_image)
                RateShortName.IQD -> Pair(R.string.rates_iqd, R.drawable.ic_rate_unknown_image)
                RateShortName.IRR -> Pair(R.string.rates_irr, R.drawable.ic_rate_unknown_image)
                RateShortName.INR -> Pair(R.string.rates_inr, R.drawable.ic_rate_inr_image)
                RateShortName.ISK -> Pair(R.string.rates_isk, R.drawable.ic_rate_isk_image)
                RateShortName.JPY -> Pair(R.string.rates_jpy, R.drawable.ic_rate_jpy_image)
                RateShortName.KRW -> Pair(R.string.rates_krw, R.drawable.ic_rate_krw_image)
                RateShortName.MXN -> Pair(R.string.rates_mxn, R.drawable.ic_rate_mxn_image)
                RateShortName.MYR -> Pair(R.string.rates_myr, R.drawable.ic_rate_myr_image)
                RateShortName.NOK -> Pair(R.string.rates_nok, R.drawable.ic_rate_nok_image)
                RateShortName.NZD -> Pair(R.string.rates_nzd, R.drawable.ic_rate_nzd_image)
                RateShortName.PHP -> Pair(R.string.rates_php, R.drawable.ic_rate_php_image)
                RateShortName.PLN -> Pair(R.string.rates_pln, R.drawable.ic_rate_pln_image)
                RateShortName.RON -> Pair(R.string.rates_ron, R.drawable.ic_rate_ron_image)
                RateShortName.RUB -> Pair(R.string.rates_rub, R.drawable.ic_rate_rub_image)
                RateShortName.SEK -> Pair(R.string.rates_sek, R.drawable.ic_rate_sek_image)
                RateShortName.SGD -> Pair(R.string.rates_sgd, R.drawable.ic_rate_sgd_image)
                RateShortName.THB -> Pair(R.string.rates_thb, R.drawable.ic_rate_thb_image)
                RateShortName.USD -> Pair(R.string.rates_usd, R.drawable.ic_rate_us_image)
                RateShortName.ZAR -> Pair(R.string.rates_zar, R.drawable.ic_rate_zar_image)
                else -> {
                    Log.e(TAG, "Could not find name and image for:$shortName")
                    Pair(R.string.rates_unknown, R.drawable.ic_rate_unknown_image)
                }
            }
        }
    }
}