package ru.laushkina.rates.model

enum class RateShortName {
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BTC,
    BTN,
    BWP,
    BYN,
    BYR,
    BZD,
    CAD,
    CDF,
    CHF,
    CLF,
    CLP,
    CNY,
    COP,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GGP,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    IMP,
    INR,
    IQD,
    IRR,
    ISK,
    JEP, //"": "Jersey Pound",
    JMD, //"": "Jamaican Dollar",
    JOD, //"": "Jordanian Dinar",
    JPY,
    KES, //"": "Kenyan Shilling",
    KGS, //"": "Kyrgystani Som",
    KHR, //"": "Cambodian Riel",
    KMF, //"": "Comorian Franc",
    KPW, //"": "North Korean Won",
    KRW,
    KWD, //"": "Kuwaiti Dinar",
    KYD, //"": "Cayman Islands Dollar",
    KZT, //"": "Kazakhstani Tenge",
    LAK, //"": "Laotian Kip",
    LBP, //"": "Lebanese Pound",
    LKR, //"": "Sri Lankan Rupee",
    LRD, //"": "Liberian Dollar",
    LSL, //"": "Lesotho Loti",
    LTL, //"": "Lithuanian Litas",
    LVL, //"": "Latvian Lats",
    LYD, //"": "Libyan Dinar",
    MAD, //"": "Moroccan Dirham",
    MDL, //"": "Moldovan Leu",
    MGA, //"": "Malagasy Ariary",
    MKD, //"": "Macedonian Denar",
    MMK, //"": "Myanma Kyat",
    MNT, //"": "Mongolian Tugrik",
    MOP, //"": "Macanese Pataca",
    MRO, //"": "Mauritanian Ouguiya",
    MUR, //"": "Mauritian Rupee",
    MVR, //"": "Maldivian Rufiyaa",
    MWK, //"": "Malawian Kwacha",
    MXN,
    MYR,
    MZN, //"": "Mozambican Metical",
    NAD, //"": "Namibian Dollar",
    NGN, //"": "Nigerian Naira",
    NIO, //"": "Nicaraguan Córdoba",
    NOK,
    NPR, //"": "Nepalese Rupee",
    NZD,
    OMR, //"": "Omani Rial",
    PAB, //"": "Panamanian Balboa",
    PEN, //"": "Peruvian Nuevo Sol",
    PGK, //"": "Papua New Guinean Kina",
    PHP,
    PKR, //"": "Pakistani Rupee",
    PLN,
    PYG, //"": "Paraguayan Guarani",
    QAR, //"": "Qatari Rial",
    RON,
    RSD, //"": "Serbian Dinar",
    RUB,
    RWF, //"": "Rwandan Franc",
    SAR, //"": "Saudi Riyal",
    SBD, //"": "Solomon Islands Dollar",
    SCR, //"": "Seychellois Rupee",
    SDG, //"": "Sudanese Pound",
    SEK,
    SGD,
    SHP, //"": "Saint Helena Pound",
    SLL, //"": "Sierra Leonean Leone",
    SOS, //"": "Somali Shilling",
    SRD, //"": "Surinamese Dollar",
    STD, //"": "São Tomé and Príncipe Dobra",
    SVC, //"": "Salvadoran Colón",
    SYP, //"": "Syrian Pound",
    SZL, //"": "Swazi Lilangeni",
    THB,
    TJS, //"": "Tajikistani Somoni",
    TMT, //"": "Turkmenistani Manat",
    TND, //"": "Tunisian Dinar",
    TOP, //"": "Tongan Paʻanga",
    TRY, //"": "Turkish Lira",
    TTD, //"": "Trinidad and Tobago Dollar",
    TWD, //"": "New Taiwan Dollar",
    TZS, //"": "Tanzanian Shilling",
    UAH, //"": "Ukrainian Hryvnia",
    UGX, //"": "Ugandan Shilling",
    USD,
    UYU, //"": "Uruguayan Peso",
    UZS, //"": "Uzbekistan Som",
    VEF, //"": "Venezuelan Bolívar Fuerte",
    VND, //"": "Vietnamese Dong",
    VUV, //"": "Vanuatu Vatu",
    WST, //"": "Samoan Tala",
    XAF, //"": "CFA Franc BEAC",
    XAG, //"": "Silver (troy ounce)",
    XAU, //"": "Gold (troy ounce)",
    XCD, //"": "East Caribbean Dollar",
    XDR, //"": "Special Drawing Rights",
    XOF, //"": "CFA Franc BCEAO",
    XPF, //"": "CFP Franc",
    YER, //"": "Yemeni Rial",
    ZAR,
    ZMK, //"": "Zambian Kwacha (pre-2013)",
    ZMW, //"": "Zambian Kwacha",
    ZWL, //"": "Zimbabwean Dollar"
    UNKNOWN;

    companion object {
        fun parse(shortName: String): RateShortName {
            return try {
                valueOf(shortName)
            } catch (exception: IllegalArgumentException) {
                UNKNOWN
            }
        }
    }
}